# TCL File Generated by Component Editor 18.1
# Sun Jun 09 16:07:19 CHOT 2019
# DO NOT MODIFY


# 
# new_component "new_component" v1.0
#  2019.06.09.16:07:19
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module new_component
# 
set_module_property DESCRIPTION ""
set_module_property NAME new_component
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME new_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE false
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 

# 
# parameters
# 


# 
# display items
# 


# 
# connection point axs_s0
# 
add_interface axs_s0 axi4 end
set_interface_property axs_s0 associatedClock clock
set_interface_property axs_s0 associatedReset reset
set_interface_property axs_s0 readAcceptanceCapability 1
set_interface_property axs_s0 writeAcceptanceCapability 1
set_interface_property axs_s0 combinedAcceptanceCapability 1
set_interface_property axs_s0 readDataReorderingDepth 1
set_interface_property axs_s0 bridgesToMaster ""
set_interface_property axs_s0 ENABLED true
set_interface_property axs_s0 EXPORT_OF ""
set_interface_property axs_s0 PORT_NAME_MAP ""
set_interface_property axs_s0 CMSIS_SVD_VARIABLES ""
set_interface_property axs_s0 SVD_ADDRESS_GROUP ""

add_interface_port axs_s0 axs_s0_awid awid Input 4
add_interface_port axs_s0 axs_s0_awaddr awaddr Input 32
add_interface_port axs_s0 axs_s0_awlen awlen Input 8
add_interface_port axs_s0 axs_s0_awsize awsize Input 3
add_interface_port axs_s0 axs_s0_awburst awburst Input 2
add_interface_port axs_s0 axs_s0_awvalid awvalid Input 1
add_interface_port axs_s0 axs_s0_awready awready Output 1
add_interface_port axs_s0 axs_s0_wdata wdata Input 32
add_interface_port axs_s0 axs_s0_wstrb wstrb Input 4
add_interface_port axs_s0 axs_s0_wvalid wvalid Input 1
add_interface_port axs_s0 axs_s0_wready wready Output 1
add_interface_port axs_s0 axs_s0_bid bid Output 4
add_interface_port axs_s0 axs_s0_bvalid bvalid Output 1
add_interface_port axs_s0 axs_s0_bready bready Input 1
add_interface_port axs_s0 axs_s0_arid arid Input 4
add_interface_port axs_s0 axs_s0_araddr araddr Input 32
add_interface_port axs_s0 axs_s0_arlen arlen Input 8
add_interface_port axs_s0 axs_s0_arsize arsize Input 3
add_interface_port axs_s0 axs_s0_arburst arburst Input 2
add_interface_port axs_s0 axs_s0_arvalid arvalid Input 1
add_interface_port axs_s0 axs_s0_arready arready Output 1
add_interface_port axs_s0 axs_s0_rid rid Output 4
add_interface_port axs_s0 axs_s0_rdata rdata Output 32
add_interface_port axs_s0 axs_s0_rlast rlast Output 1
add_interface_port axs_s0 axs_s0_rvalid rvalid Output 1
add_interface_port axs_s0 axs_s0_rready rready Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_reset reset Input 1

