set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_ALE]
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_CE]
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_CLE]
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_RE]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_RB] -to *
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ0]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ1]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ2]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ3]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ4] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ4]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ5] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ5]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ6] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ6]
set_false_path -from [get_ports hps_io_hps_io_nand_inst_DQ7] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_DQ7]
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_WP]
set_false_path -from * -to [get_ports hps_io_hps_io_nand_inst_WE]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D0] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D0]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D1] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D1]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D2] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D2]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D3] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D3]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D4] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D4]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D5] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D5]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D6] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D6]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_D7] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_D7]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_CLK] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_usb1_inst_STP]
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_DIR] -to *
set_false_path -from [get_ports hps_io_hps_io_usb1_inst_NXT] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_CLK]
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_MOSI]
set_false_path -from [get_ports hps_io_hps_io_spim0_inst_MISO] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_spim0_inst_SS0]
set_false_path -from [get_ports hps_io_hps_io_uart0_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_uart0_inst_TX]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SDA] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SDA]
set_false_path -from [get_ports hps_io_hps_io_i2c0_inst_SCL] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_i2c0_inst_SCL]
set_false_path -from [get_ports hps_io_hps_io_can1_inst_RX] -to *
set_false_path -from * -to [get_ports hps_io_hps_io_can1_inst_TX]